### DISCUSSION TITLE
Levels of diagnostic logs in AKS

### DISCUSSION THREAD

**Discussion by Gordonby** [Azure/PSRule.Rules.Azure#1036] [Q&A] [answered]
My deployment is failing on this rule.

Rule: Azure.AKS.PlatformLogs
Reason: The diagnostic setting (aksDiags) logs should enable (cluster-autoscaler, kube-apiserver, kube-controller-manager, kube-scheduler, AllMetrics).

However the AKS Secure Baseline Cluster Stamp (which is generally the go-to reference implementation), only configures 4
cluster-autoscaler, kube-controller-manager, kube-audit-admin, guard.

ref: [https://github.com/mspnp/aks-secure-baseline/blob/ed5206c3b1cb620a089201951290580857961ea4/cluster-stamp.json#L1227](https://github.com/mspnp/aks-secure-baseline/blob/ed5206c3b1cb620a089201951290580857961ea4/cluster-stamp.json#L1227)

**Comment by BernieWhite** [comment, marked as answer]
@Gordonby That is fair. The implementation was based on https://docs.microsoft.com/en-gb/azure/aks/monitor-aks#collect-resource-logs which does suggest AllMetrics should be logged but I can see why that may not be desired.

Does it help to know that you can override the default configuration with the following to remove `AllMetrics`?

```yaml
# YAML: The default AZURE_AKS_ENABLED_PLATFORM_LOG_CATEGORIES_LIST configuration option
configuration:
  AZURE_AKS_ENABLED_PLATFORM_LOG_CATEGORIES_LIST: ['cluster-autoscaler', 'kube-apiserver', 'kube-controller-manager', 'kube-scheduler']
```

@ArmaanMcleod Thoughts?
