### DISCUSSION TITLE
A pure preview baseline

### DISCUSSION THREAD

**Discussion by Gordonby** [Azure/PSRule.Rules.Azure#1121] [Ideas]
Having the ability to run baselines for different rulessets is great. However I have the situation where
1. I want visibility of preview rules, so I can investigate features, read the docs and understand the context
2. I don't really want my CI/CD build to fail for failing of preview rules

A way to deal with this could be to run PSRule twice in my pipeline.
The first step uses a GA baseline, and the step will fail if there any errors in PSRule.
The seconds step uses a Preview baseline, and the step will be set to continue on failure.

This accomplishes what I require, but is not efficient because I'm retesting the same GA rules twice.
I almost want a baseline that is "Just preview rules", or a way of easily taking two baselines and substracting the delta between them and then just running those rules.

Thoughts?

**Comment by BernieWhite** [comment]
@Gordonby Makes sense should be fine.

**Reply by BernieWhite** [reply]
@Gordonby You can make your own baseline by creating a `.Rule.yaml` file in the `.ps-rule/` path with the following:

```yaml
---
# Synopsis: Include rules released September 2021 or prior for Azure preview only features.
apiVersion: github.com/microsoft/PSRule/v1
kind: Baseline
metadata:
  name: Local.Azure.Preview_2021_09
spec:
  rule:
    tag:
      release: preview
      ruleSet:
      - '2020_06'
      - '2020_09'
      - '2020_12'
      - '2021_03'
      - '2021_06'
      - '2021_09'
```

But is does make me think we could look at enabling similar scenarios in different ways in the future. Maybe allow all the preview flagged rules to just generate warning instead.

Also I think other customers may want this feature so I'll put in on the back log.
