### DISCUSSION TITLE
Bicep files via parameterfiles not processed.

### DISCUSSION THREAD

**Discussion by JonasCordsen** [Azure/PSRule.Rules.Azure#1545] [Q&A] [answered]
Hello

I have been running some tests, and I cannot seem to get the rules (Baseline rules) to hit the bicep files and modules.

I get a lot of warnings " has not been processed because no matching rules were found.", it only seems like It is running rules agents the parameter files.

I have setup the parameter files to find my main bicep via metadata.

What am I missing, or why is the PSrule not analysing the Bicep code

I have linked a screenshot and the ps-rule.yaml file
![Screenshot 2022-08-03 at 15 00 11](https://user-images.githubusercontent.com/106592722/182614109-ed33b58f-e670-4797-92b6-000098d9a323.png)

PS-rule.yaml file
```

# Options can be found here: https://github.com/microsoft/PSRule/blob/main/docs/concepts/PSRule/en-US/about_PSRule_Options.md
requires:
  # Require a minimum of PSRule for Azure v1.10.2
  PSRule.Rules.Azure: '>=1.10.2'

configuration:
  # Enable expansion of Azure Template files.
  AZURE_PARAMETER_FILE_EXPANSION: true
  AZURE_PARAMETER_FILE_METADATA_LINK: true

  # Enable expansion of Azure Bicep files.
  AZURE_BICEP_FILE_EXPANSION: false
  AZURE_BICEP_FILE_EXPANSION_TIMEOUT: 60

  CAF_ResourceGroupMandatoryTags: 
  - 'Responsible'
  - 'CostCenter'

  # Specify the tag (key) and valid values
  CAF_EnvironmentTag: 'Environment'
  CAF_Environments:
  - 'dev'
  - 'prod'

  #Specify the Baseline to scan agents https://azure.github.io/PSRule.Rules.Azure/en/baselines/Azure.All/
  baseline: Azure.All

input:
  # Specify the folders/Files to exclude from scanning
  pathIgnore:
   # - 'out/'
   # - 'tests/'
   - templates/**/*.bicep

execution:
  # Leaving this at default (true)
  # We want to make sure we have at least one test for all objects
  notProcessedWarning: true

include:
  module:
    - PSRule.Rules.Azure
    - PSRule.Rules.CAF

output:
  style: Client
  format: NUnit3
  path: tmp/TEST-PSRule.xml

#rule:
  # Automatically include all local rules in the search path unless they have been explicitly excluded
  #includeLocal: true
  #exclude:
  # Ignore the following rules for all resources
  #- Azure.VM.UseHybridUseBenefit
  #- Azure.VM.Standalone
```

**Comment by BernieWhite** [comment, marked as answer]
@JonasCordsen From the screenshot to looks like the Bicep code is being expanded because `helper` comes from this process. The resource names that would be created via the parameter files should appear in the output.

It looks like the binding configuration that associates the type of each resource is not being applied.

---

Previously there was a bug if you executed both _PSRule.Rules.Azure_ with _PSRule.Rules.CAF_ but this should be fixed if you are using the latest versions of PSRule v2.2.0 and PSRule for Azure v1.17.1.

I don't see _PSRule.Rules.CAF_ in the output but it seems to be in the `ps-rule.yaml` file.

---

I can't see anything in the `ps-rule.yaml` file, however if you are developing custom rules, then you may have set some `binding` options, because the bindings from _PSRule.Rules.Azure_ are scoped to only apply to rules within _PSRule.Rules.Azure_.

If you set these bindings within `ps-rule.yaml` or via environment variables they override the settings in _PSRule.Rules.Azure_ which can cause this problem.

See. https://azure.github.io/PSRule.Rules.Azure/customization/enforce-custom-tags/#bindingtype

---

If none of these suggestions are true, it may be a bug. To debug further set these options in `ps-rule.yaml` and try running `Assert-PSRule` with `-Verbose` to help work out what is happening.

```yaml
# Configure binding for local rules.
binding:
  preferTargetInfo: true
  targetType:
  - type
  - resourceType

# Require minimum versions of modules.
requires:
  PSRule: '>=2.2.0'
  PSRule.Rules.Azure: '>=1.17.1'
```
