### DISCUSSION TITLE
Exception calling "GetBicepResources" with "3" argument(s): "Unable to expand resources because the source file

### DISCUSSION THREAD

**Discussion by oxbo-andre** [Azure/PSRule.Rules.Azure#1581] [Q&A] [answered]
Github Actions workflows fail to expand and use bicep template with error:
Failed to expand bicep source '...\main.bicep'. Exception calling "GetBicepResources" with "3" argument(s): "Unable to expand resources because the source file '...\main.bicep' was not valid. An error occurred evaluating expression '[length(parameters('resourcegroupNames'))]' line 66. The parameter named 'resourcegroupNames' was not set or a defaultValue was defined."

Steps to reproduce the issue:

```powershell

```

**Expected behaviour**

No error, expand the bicep file.

```text

```

**Module in use and version:**

- Module: PSRule.Rules.Azure
- Version: 1.18.1

Captured output from `$PSVersionTable`:

```text
Name                           Value
----                           -----
PSVersion                      7.2.[6]
PSEdition                      Core
GitCommitId                    [7].2.6
OS                             Linux 5.15.0-[10]17-azure #20~20.04.1-Ubuntu SMP …
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Additional context**

**Comment by aavdberg** [comment]
> Github Actions workflows fail to expand and use bicep template with error: Failed to expand bicep source '...\main.bicep'. Exception calling "GetBicepResources" with "3" argument(s): "Unable to expand resources because the source file '...\main.bicep' was not valid. An error occurred evaluating expression '[length(parameters('resourcegroupNames'))]' line 66. The parameter named 'resourcegroupNames' was not set or a defaultValue was defined."
> 
> Steps to reproduce the issue:
> 
> **Expected behaviour**
> 
> No error, expand the bicep file.
> 
> ```
> 
> ```
> 
> **Module in use and version:**
> 
> * Module: PSRule.Rules.Azure
> * Version: 1.18.1
> 
> Captured output from `$PSVersionTable`:
> 
> ```
> Name                           Value
> ----                           -----
> PSVersion                      7.2.[6]
> PSEdition                      Core
> GitCommitId                    [7].2.6
> OS                             Linux 5.15.0-[10]17-azure #20~20.04.1-Ubuntu SMP …
> Platform                       Unix
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0
> ```
> 
> **Additional context**

main.bicep:

param resourcegroupNames array

main.parma.bicep.json:

    "resourcegroupNames": {
      "value": [
        {
          "name": "acr",
          "environmentType": "prod"
        },
        {
          "name": "kv",
          "environmentType": "prod"
        }
      ]
    }

**Comment by BernieWhite** [comment, marked as answer]
@oxbo-andre Thanks for reporting the issue.

Expansion requires a parameter file or other bicep deployment referencing the module to provide required parameters.

If you have a parameter file as the post from @aavdberg may suggest then try this:

1. Double check that the Bicep module `main.bicep` is excluded. You can do this by setting the `Input.PathIgnore` option. This is because expansion occurs from the parameter file or other bicep file, so the referenced module needs to be excluded.

Details here: https://azure.github.io/PSRule.Rules.Azure/using-bicep/#configuringpathexclusions

2. Alternatively, you may consider setting default values (via `AZURE_PARAMETER_DEFAULTS`) for testing, but that is mostly is designed around common parameters provided by a deployment pipeline. In your case this doesn't seem applicable.

See: https://azure.github.io/PSRule.Rules.Azure/setup/configuring-expansion/#requiredparameterdefaults

---

Things to note, PSRule will automatically find the .bicep file from the parameter file only if:

- Metadata link - An association between parameter file to bicep file via metadata in the parameter file. See https://azure.github.io/PSRule.Rules.Azure/using-templates/#linkingtemplates
- ~~Naming convention~~: This currently doesn't work for Bicep files. That is a bug I found while double checking your scenario. Currently the naming convention is not configurable it has to be `<deployment>.parameters.json`.

You can also enforce the metadata link be setting the `AZURE_PARAMETER_FILE_METADATA_LINK` option, to ensure parameter files are not left unaccounted for.

https://azure.github.io/PSRule.Rules.Azure/setup/configuring-expansion/#requiretemplatemetadatalink

Parameter file expansion needs to be enabled via `AZURE_PARAMETER_FILE_EXPANSION`.

https://azure.github.io/PSRule.Rules.Azure/setup/configuring-expansion/#parameterfileexpansion

---

I hope that helps. If not, then let me know and we might need to debug it further by collecting some additional information.

**Comment by aavdberg** [comment]
Hi @BernieWhite i opened the issue with my working account and commented with my own account.

Linking the parameter file to the template file is not mentioned in the documentatie for Bicep.

my main bicep file is: main.bicep 
and my parameter file is main.params.bicep.json.

**Comment by BernieWhite** [comment]
@aavdberg Thanks for the feedback.

Here are the links:

- https://azure.github.io/PSRule.Rules.Azure/using-bicep/#usingparameterfiles
- https://azure.github.io/PSRule.Rules.Azure/using-bicep/#configuringpathexclusions

But based on your feedback we still have work to do to make it clearer :) thanks.

**Comment by aavdberg** [comment]
This is my ps.rule.yaml file:

```yaml
include:
  module:
    - PSRule.Rules.Azure

output:
  culture:
    - "en-US"

input:
  pathIgnore:
    # Ignore other files in the repository.
    - ".vscode/"
    - ".github/"
    - "*.md"
    - "*.yaml"
    - "bicepconfig.json"
    - "*.azcli"

  # Exclude modules but not tests.
  #- 'bicep/modules/**/*.bicep'
  #- '!bicep/modules/**/*.tests.bicep'

execution:
  notProcessedWarning: false

configuration:
  # Enable automatic expansion of Azure parameter files.
  AZURE_PARAMETER_FILE_EXPANSION: true

  # Enable automatic expansion of Azure Bicep source files.
  AZURE_BICEP_FILE_EXPANSION: true

  # Configures the number of seconds to wait for build Bicep files.
  AZURE_BICEP_FILE_EXPANSION_TIMEOUT: 20

```

**Comment by aavdberg** [comment]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/22030609/185142131-15a0f75a-c34e-4d1a-ad0f-55001961dc21.png">

**Comment by BernieWhite** [comment]
@aavdberg Nice! Looks mostly good just uncomment: `  #- 'bicep/modules/**/*.bicep'` and update the path where your Bicep files are located if they are not in the `bicep/modules/` directory within your repository.

To metadata link your parameter file it might look something like this if the file `main.bicep` is in the same directory as the parameter file.

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "metadata": {
        "template": "./main.bicep"
    },
    "parameters": {
        "resourcegroupNames": {
            "value": [
              {
                "name": "acr",
                "environmentType": "prod"
              },
              {
                "name": "kv",
                "environmentType": "prod"
              }
            ]
          }
    }
}
```

**Comment by BernieWhite** [comment]
> <img alt="image" width="722" src="https://user-images.githubusercontent.com/22030609/185142131-15a0f75a-c34e-4d1a-ad0f-55001961dc21.png">

The warning in the parameter file schema is not strictly correct. `metadata` can be defined on almost any property without impact. It's ignored by ARM is most cases except for a few edge cases. Either way, it's fine to add to the parameter file.

**Comment by aavdberg** [comment]
With modules you mean that i use in my main.bicep file? The modules are in an Azure Container Registry.

**Comment by aavdberg** [comment]
Looks better now 🚀
<img width="750" alt="image" src="https://user-images.githubusercontent.com/22030609/185144208-ee87611e-1f42-4995-979f-715d26a855fc.png">

```yaml
include:
  module:
    - PSRule.Rules.Azure

output:
  culture:
    - "en-US"

input:
  pathIgnore:
    # Ignore other files in the repository.
    - ".vscode/"
    - ".github/"
    - "*.md"
    - "*.yaml"
    - "bicepconfig.json"
    - "*.azcli"

  # Exclude modules but not tests.
  #  - 'bicep/modules/**/*.bicep'
  # - '!bicep/modules/**/*.tests.bicep'

execution:
  notProcessedWarning: false

configuration:
  # Enable automatic expansion of Azure parameter files.
  AZURE_PARAMETER_FILE_EXPANSION: true

  # Enable automatic expansion of Azure Bicep source files.
  AZURE_BICEP_FILE_EXPANSION: false

  # Configures the number of seconds to wait for build Bicep files.
  AZURE_BICEP_FILE_EXPANSION_TIMEOUT: 20

```

**Comment by BernieWhite** [comment]
@aavdberg You can use Bicep code with PSRule in the following ways:

- Bicep deployment (i.e. `deploy.bicep`) with no required parameters -> Bicep module (i.e. `main.bicep`) stored in Azure Container Registry or via a local relative path.
- JSON parameter file -> Bicep module (i.e. `main.bicep`) stored in Azure Container Registry or via a local relative path.

Also you can also: Bicep deployment/ parameter file -> Bicep module -> Bicep module ....

If you are using the PSRule integration with GitHub Actions or Azure Pipelines then see the following to make sure that the context PSRule runs under has an authenticated connection to be able to complete the restore.

https://azure.github.io/PSRule.Rules.Azure/using-bicep/#restoringmodulesfromaprivateregistry

--- 

Alternatively if the modules are already directly restored prior to calling PSRule with a `bicep build` or `az bicep build` then the modules will already be cached locally.

**Comment by BernieWhite** [comment]
> Looks better now 🚀

@aavdberg Nice!

**Comment by aavdberg** [comment]
Thanks @BernieWhite 

```yaml
jobs:
  validate:
    name: Analyze templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Display PowerShell version
      - name: PowerShell version
        run: |
         $PSVersionTable
        shell: pwsh

      # Login to Azure for access to Azure Container Registry
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_IDENTITY_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      # Analyze Azure resources using PSRule for Azure
      - name: Analyze Azure template files
        uses: microsoft/ps-rule@v2.3.2
        with:
          modules: "PSRule.Rules.Azure"
```

Using GitHub Actions workflows
