### DISCUSSION TITLE
PSRule.Rules.Azure how to scan only a certain path in repository?

### DISCUSSION THREAD

**Discussion by oxbo-andre** [Azure/PSRule.Rules.Azure#1584] [Q&A] [answered]
I was looking how to specify in the workflow which repository path to assest and found that you have the option args: but can't find any documentatie about it.

So have the following in my iac.yml file:

```yaml
      # Analyze Azure resources using PSRule for Azure
      - name: Analyze Azure template files
        uses: microsoft/ps-rule@v2.3.2
        with:
          modules: "PSRule.Rules.Azure"
          args: 
```

**Comment by oxbo-andre** [comment]
already found it, I think

```yaml
      # Analyze Azure resources using PSRule for Azure
      - name: Analyze Azure template files
        uses: microsoft/ps-rule@v2.3.2
        with:
          modules: "PSRule.Rules.Azure"
          inputType: inputPath
          inputPath: '${{ github.workspace }}\Azure\Templates\ALZ\IAC\'

```

**Comment by oxbo-andre** [comment]
Getting now a error that the assertions failed but not the reason for it

![image](https://user-images.githubusercontent.com/108665873/185370409-aee4f931-a821-4d4c-b501-b3f3d7da2440.png)

**Reply by BernieWhite** [reply]
@oxbo-andre Try flipping the slashes on your input path for Linux.

If that doesn't work you can set the `ACTIONS_STEP_DEBUG` environment variable to `true`.

See https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging

---

Also remember that Linux is case-sensitive so the input path needs to exactly match.

**Reply by aavdberg** [reply]
Don't work and debug setting don't show more in the logs.

**Reply by BernieWhite** [reply]
@aavdberg Ok thanks. Can you please update your GitHub action to use `microsoft/ps-rule@debug` instead of `microsoft/ps-rule@v2.3.2`.

Hopefully that will return more information.

**Comment by oxbo-andre** [comment]
https://github.com/microsoft/ps-rule/discussions/141

**Comment by BernieWhite** [comment]
@oxbo-andre @aavdberg You can find the available options for the GitHub Action over here: https://github.com/microsoft/ps-rule

---

There is two possible options that will probably be of interest:

- `inputPath` - Configures the input path to scan for Azure IaC. I.e. If you want to only scan for files in `azure/templates/`.
- `path` - Configures the root/ working path that PSRule runs from. This affects the path that is scanned from similar to `inputPath` but it also affects the location PSRule will look for the `ps-rule.yaml` options file and `.ps-rule/` directory for custom rules. Everything will be under the specified working path.

**Note:** PSRule for Azure will not work with `inputType` is set to `inputPath`. It must be set to `repository`, which is the default.

Even if you use the default `inputType` or specifically set it to `repository`, you can still use the `inputPath` parameter to set the path PSRule scans for Azure IaC from. They are not mutually exclusive.

---

I hope that helps.

**Reply by aavdberg** [reply]
change the inputType to repository and sill not working and also not with / slash instead of \

**Comment by oxbo-andre** [comment]
This output is from a other workflow where I check the root of the repository with the following:

analyze-arm.yml:

```yaml
      # Analyze Azure resources using PSRule for Azure
      - name: Analyze Azure template files
        uses: microsoft/ps-rule@v2.3.2
        with:
          modules: "PSRule.Rules.Azure"
```

![image](https://user-images.githubusercontent.com/108665873/185389178-88095323-e99c-4d74-8851-107b979347a0.png)

But when I define the inputPath in the iac.yml:

```yaml
      # Analyze Azure resources using PSRule for Azure
      - name: Analyze Azure template files
        uses: microsoft/ps-rule@v2.3.2
        with:
          modules: "PSRule.Rules.Azure"
          inputType: repository
          inputPath: '${{ github.workspace }}/Azure/Templates/ALZ/IAC/**'
          prerelease: true
```

![image](https://user-images.githubusercontent.com/108665873/185389500-d7f296ec-1866-4551-bfad-2235d20ceddb.png)
