### DISCUSSION TITLE
Exclude per filename/path regex option

### DISCUSSION THREAD

**Discussion by juju4** [Azure/PSRule.Rules.Azure#2033] [Q&A] [answered]
**Is your feature request related to a problem? Please describe.**

There should be an option to exclude by filename/path pattern (wildcard or regex), not just by rule

For example, processing [Azure-Sentinel](https://github.com/Azure/Azure-Sentinel/) repo and want to exclude invalid test files
Else, get irrelevant warnings/errors ("Error: Failed to deserialize the file")

Example: https://github.com/juju4/Azure-Sentinel/actions/runs/4152879216/jobs/7184135632#step:3:40398

**Describe the solution you'd like**

Something like pre-commit setting
https://pre-commit.com/#regular-expressions
```
    -   id: my-hook
        exclude: |
            (?x)^(
                path/to/file1.py|
                path/to/file2.py|
                path/to/file3.py
            )$
```

from https://microsoft.github.io/PSRule/v2/concepts/PSRule/en-US/about_PSRule_Options/#ruleexclude
```
# YAML: Using the rule/exclude property
rule:
  exclude:
  - Rule3
  - Rule4

# Bash: Using environment variable
export PSRULE_RULE_EXCLUDE='Rule3;Rule4'

# GitHub Actions: Using environment variable
env:
  PSRULE_RULE_EXCLUDE: 'Rule3;Rule4'

# Azure Pipelines: Using environment variable
variables:
- name: PSRULE_RULE_EXCLUDE
  value: 'Rule3;Rule4'
```

we could have
```
# YAML: Using the rule/exclude property
file:
  exclude:
  - invalidjson.json
  - *tmp*
  - *.md
  - *.png

# Bash: Using environment variable
export PSRULE_FILE_EXCLUDE='invalidjson.json;*tmp*'

# GitHub Actions: Using environment variable
env:
  PSRULE_FILE_EXCLUDE: 'invalidjson.json;*tmp*'

# Azure Pipelines: Using environment variable
variables:
- name: PSRULE_FILE_EXCLUDE
  value: 'invalidjson.json;*tmp*'
```

**Describe alternatives you've considered**

Use rule exclusion but not relevant for known invalid json (error on deserialization)

**Comment by BernieWhite** [comment, marked as answer]
@juju4 Thanks for raising an issue. I think we can answer this one as a question so I've move it here so that it might help others in the community.

I believe the option you are looking for is [Input.PathIgnore](https://microsoft.github.io/PSRule/v2/concepts/PSRule/en-US/about_PSRule_Options/#inputpathignore).

This option uses the same format as a git path spec, which is not strictly a regular expression but should meet most requirements.

For example:

```yaml
input:
  pathIgnore:
  - invalidjson.json
  - *tmp*
  - *.md
  - *.png
```

Which also means you can do this:

```yaml
input:
  pathIgnore:
  # Remove all files
  - '*'
  # Add back files that are interesting
  - '!**/deploy.bicep'
```

Another example is here: https://azure.github.io/PSRule.Rules.Azure/using-bicep/#using-parameter-files

---

Is this what you are after?

**Reply by juju4** [reply]
Thanks for your patience.
Yes, that's what I was looking for, but it does not seem to work in my context (ADO)

using following job template
```
jobs:
- job: "psruleValidation"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: ps-rule-assert@2
      displayName: Analyze Azure template files
      inputs:
        modules: 'PSRule.Rules.Azure'
        pathIgnore:
          - .script/tests/.../file.json
          - .scripts/tests/file2.json
          - '*.md'
          - '*.png'
        continueOnError: true
```
resulting in
```
/.azure-pipelines/psruleValidation.yaml (Line: 14, Col: 11): A sequence was not expected
```
Line being the first value in pathIgnore

Thanks

**Reply by BernieWhite** [reply]
@juju4 There is a limited number of options that are configurable directly in the Azure DevOps task and [Input.PathIgnore](https://microsoft.github.io/PSRule/v2/concepts/PSRule/en-US/about_PSRule_Options/#inputpathignore) is not one of these that can be directly configured using `input:` however you can **use an environment variable**.

For most cases, the easiest what you can configure this option is by creating a `ps-rule.yaml` file within the root of your repository and adding the option.

That way if you are running locally within VSCode or within Azure DevOps you get the same experience

To do this create a `ps-rule.yaml` file with the following content.

```yaml
input:
  pathIgnore:
  - .script/tests/.../file.json
  - .scripts/tests/file2.json
  - '*.md'
  - '*.png'
```

And that should work.

To configure using the environment variable option, you could use:

```yaml
jobs:
- job: "psruleValidation"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: ps-rule-assert@2
      displayName: Analyze Azure template files
      continueOnError: true
      env:
        PSRULE_INPUT_PATHIGNORE: '.script/tests/**/file.json;.scripts/tests/file2.json;*.md;*.png'
      inputs:
        modules: 'PSRule.Rules.Azure'
```
