### DISCUSSION TITLE
Unable to expand the Parameters in .bicepparam files

### DISCUSSION THREAD

**Discussion by AhmedValiShaik** [Azure/PSRule.Rules.Azure#3137] [Q&A] [answered]
I have a folder structure like below

```
-.ps-rule
	-Org.Tags.Rule.yaml
-infra
	- modules
		- storageAccount.bicep
	- parameters
		-main.dev.bicepparam
		-main.test.bicepparam
	-main.bicep
-ps-rule.yaml
```

My main.bicep looks like this
```
param location string = resourceGroup().location
param responsible string
param env string
param module string
param logWSName string
param sharedResourceGroup string

var defaultTags = {
    module: module
    Environment: env
    Responsible: responsible
}

resource logAnalyticsWorkspaceRes 'Microsoft.OperationalInsights/workspaces@2022-10-01' existing = {
  name:logWSName
  scope:resourceGroup(sharedResourceGroup)
}

module storageAccModule 'modules/storageAccount.bicep'= {
  name: 'StorageAccDeployment_${utcValue}'
  params: {
    env:env
    defaultTags:defaultTags
    location: location
    logAnalyticsWSId: logAnalyticsWorkspaceRes.id
  }
}
```
My param file looks like this
```
using '../main.bicep'

param env = 'Demo'
param module = 'Test'
param sharedResourceGroup = 'Test'
param logWSName = 'Test'
```
My ps-rule.yaml looks like this
```
binding:
  preferTargetInfo: true
  targetType:
    - type
    - resourceType

# Require minimum versions of modules.
requires:
  PSRule: '>=2.9.0'
  PSRule.Rules.Azure: '>=1.39.1'

# Use PSRule for Azure.
include:
  module:
    - PSRule.Rules.Azure

output:
  culture:
    - 'en-AU'

execution:
  unprocessedObject: Ignore

input:
  pathIgnore:
    - 'infra/modules/*.bicep'
    - '!infra/main.bicep'


configuration:
  
  AZURE_RESOURCE_GROUP:
    location: 'westus'
  
  # Enable Bicep CLI checks.
  AZURE_BICEP_CHECK_TOOL: true

  # Enable automatic expansion of Azure parameter files.
  AZURE_PARAMETER_FILE_EXPANSION: true

  # Enable automatic expansion of Azure Bicep source files.
  AZURE_BICEP_FILE_EXPANSION: true

  AZURE_BICEP_PARAMS_FILE_EXPANSION: true

  # Configures the number of seconds to wait for build Bicep files.
  AZURE_BICEP_FILE_EXPANSION_TIMEOUT: 30

rule:
  # Enable custom rules that don't exist in the baseline
  includeLocal: true

```

I keep getting the error,

`"Unable to expand resources because the source file 'main.bicep' was not valid. An error occurred evaluating expression '[variables('defaultTags')]' line 80. An error occurred evaluating expression '[parameters('module')]'. The parameter named 'module' was not set or a defaultValue was defined."`

I found 2 alternatives
1. If I add the AZURE_PARAMETER_DEFAULTS configuration to the ps-rule.yaml, I dont get any error. 
```
 AZURE_PARAMETER_DEFAULTS:
    module: 'test'
    env: 'test'
    responsible: 'test'
```
2.  Make the param have an optional empty string in main.bicep
`param responsible string = ''`

Am I missing anything here in ps-rule.yaml or Is there any other way we could solve this ?
