### DISCUSSION TITLE
PSRule with Enterprise Scale Landing Zones

### DISCUSSION THREAD

**Discussion by BernieWhite** [Azure/PSRule.Rules.Azure#759] [Announcements]
We are working through how Enterprise Scale is best supported with PSRule.

If you are using the latest updates and structure from https://github.com/Azure/AzOps-Accelerator consider disabling the following rules:

- `Azure.Template.DefineParameters`
- `Azure.Template.ResourceLocation`

You can do this by adding the following to `ps-rule.yaml` in the root of your repository.

```yaml
rule:
  exclude:
  - 'Azure.Template.DefineParameters'
  - 'Azure.Template.ResourceLocation'
```

For the older style repository structure additionally consider adding these options:

```yaml
input:
  pathIgnore:
  - 'docs/'
  - 'examples/'
  - 'workloads/'
```
