### DISCUSSION TITLE
Bicep support

### DISCUSSION THREAD

**Discussion by BernieWhite** [Azure/PSRule.Rules.Azure#854] [Announcements]
We just added support for Bicep. Expansion of Bicep source files is currently experimental. You can try it out by installing PSRule for Azure v1.6.0 or newer.

https://azure.github.io/PSRule.Rules.Azure/using-bicep/
https://azure.github.io/PSRule.Rules.Azure/install-instructions/
https://azure.github.io/PSRule.Rules.Azure/creating-your-pipeline/

Let us know how you go.

**Updated**: Bicep support is generally available for use as of PSRule for Azure v1.11.0.

**Comment by smholvoet** [comment]
Hi 👋

I know this is still an experimental feature, but I'm trying to run a pre-flight validation on my bicep code, using Azure Pipelines. 

My repo structure looks like this:

```text
root
 ┣ ps-rule.yaml
 ┣ deploy
 ┃ ┗ azure-pipelines.yml
 ┃ ┗ main.bicep
 ┣ .gitignore
 ┗ README.md
```

I have all of my bicep code in a single `main.bicep` file. I also have a `ps-rule.yaml` configuration file in the root of my repo, which I don't think is required as I just have a single Bicep file. I'm using the `ubuntu-latest` Microsoft-hosted agent, which comes with Bicep [preinstalled](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#tools).

The stage which runs the pre-flight validation:

```yaml
- stage: Validate
  jobs: 
  - job: ValidateBicepCode
    displayName: Validate Bicep code
    steps:
      - task: ps-rule-install@0
        displayName: Install PSRule.Rules.Azure
        inputs:
          module: 'PSRule.Rules.Azure'

      - task: ps-rule-assert@0
        displayName: Analyze Azure template files
        inputs:
          inputType: 'inputPath'
          inputPath: './deploy/main.bicep'
          modules: 'PSRule.Rules.Azure'
          outputFormat: NUnit3
          outputPath: reports/ps-rule-resources.xml

      - task: PublishTestResults@2
        displayName: 'Publish PSRule results'
        inputs:
          testRunTitle: 'PSRule' 
          testRunner: NUnit
          testResultsFiles: 'reports/ps-rule-results.xml'
        condition: succeededOrFailed()
```

Running the stage goes fine,, however the `PSRule.Rules.Azure` rules somehow don't get applied: `##[warning]Target object 'deploy/main.bicep' has not been processed because no matching rules were found.`


The full task output:
```text
[info] Source '/home/vsts/work/1/s/.ps-rule/' does not exist.

> Checking module: PSRule.Rules.Azure
  - Already installed
  - Using version: 1.9.0

[info] Using Version: 1.8.0
[info] Using PWD: /home/vsts/work/1/s
[info] Using Path: /home/vsts/work/1/s
[info] Using Source: /home/vsts/work/1/s/.ps-rule/
[info] Using Baseline: 
[info] Using Conventions: 
[info] Using InputType: inputPath
[info] Using InputPath: /home/vsts/work/1/s/deploy/main.bicep
[info] Using OutputFormat: NUnit3
[info] Using OutputPath: /home/vsts/work/1/s/reports/ps-rule-resources.xml

---
    ____  _____ ____        __
   / __ \/ ___// __ \__  __/ /__
  / /_/ /\__ \/ /_/ / / / / / _ \
 / ____/___/ / _, _/ /_/ / /  __/
/_/    /____/_/ |_|\__,_/_/\___/

Using PSRule v1.8.0+0650c6e618bbfcd69b8fd551d2f71074464529d4
Using PSRule.Rules.Azure v1.9.0

----------------------------
Explore documentation: https://microsoft.github.io/PSRule/
Contribute and find source: https://github.com/microsoft/PSRule
Report issues: https://github.com/microsoft/PSRule/issues
PSRule.Rules.Azure: https://aka.ms/ps-rule-azure
----------------------------

##[warning]Target object 'deploy/main.bicep' has not been processed because no matching rules were found.

Rules processed: 0, failed: 0, errored: 0
Run Bicep/941 completed in 00:00:00.5961624
---
```

What am I missing here?

**Reply by BernieWhite** [reply]
@smholvoet Thanks for giving it a go. You'll find there is still a warning however the contents of the bicep file should be expanded. To enable expansion you need to set the configuration option `AZURE_BICEP_FILE_EXPANSION: true`.

See https://azure.github.io/PSRule.Rules.Azure/setup/setup-bicep/#configuringexpansion

Also note when using a single file `main.bicep` can't have any required parameters. i.e. parameters without a default value.

If you do, create a `main.tests.bicep` that references `main.bicep` with required parameters specified. Then exclude `main.bicep` with the `input.pathIgnore` option. See https://microsoft.github.io/PSRule/concepts/PSRule/en-US/about_PSRule_Options.html#inputpathignore.

**Reply by smholvoet** [reply]
Thank you @BernieWhite , that did the trick 🎉

For anyone who runs into a similar issue in the future:

1. Update the ps-rule.yaml file so it includes the `AZURE_BICEP_FILE_EXPANSION`, here's mine:

```yaml
requires:
  # Require a minimum of PSRule for Azure v1.4.1
  PSRule.Rules.Azure: '>=1.4.1'

configuration:
  # Enable automatic expansion of bicep source files
  AZURE_BICEP_FILE_EXPANSION: true
```

2. Create a `test.bicep` file and add dummy values to all parameters which don't have a [default value](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/parameters#default-value).

```bicep
@description('The administrator login username for the SQL server.')
param sqlServerAdministratorLogin string = 'dummy'

@secure()
@description('The administrator login password for the SQL server.')
param sqlServerAdministratorLoginPassword string = 'dummy'
```


3. Change the `inputPath` parameter so it points to the modified Bicep template
```yaml
  - task: ps-rule-assert@0
        displayName: Analyze Azure template files
        inputs:
          inputType: 'inputPath'
          inputPath: './deploy/tests/main.tests.bicep'
```

4. Make sure PSRule ignores the actual Bicep file which won't have any default values (I'm guessing this will only be an issue if you're using `inputType: 'repository'`)
```yaml
- name: PSRULE_INPUT_PATHIGNORE
  value: './deploy/main.bicep'
```

I might even create the `.tests.bicep` file which appends dummy values to the parameters at runtime so I don't have to make changes in 2 separate files if the validation does find any issues.

- Good news: Bicep pre-flight validation working like a charm
- Bad news: 25 validations to resolve 😂

![image](https://user-images.githubusercontent.com/13507392/139876445-a3d01b61-d78a-4e4e-bdcf-702295e23f60.png)
