### ISSUE TITLE
In-flight validation failing 

### ISSUE THREAD

**Issue by smholvoet** [Azure/PSRule.Rules.Azure#1062]
**Description of the issue**

I'm trying to run in-flight validation of already deployed resources using Azure Pipelines.

**To Reproduce**

Steps to reproduce the issue:

Below is the stage which runs the tests.
- I first install **PSRule** and the **PSRule.Rules.Azure** modules
- I then use Azure PowerShell to connect to my subscription and run the actual validation

```yaml
- stage: SmokeTest
  jobs:
  - job: SmokeTest
    displayName: Smoke test
    steps:
      - task: ps-rule-install@0
        displayName: Install PSRule.Rules.Azure
        inputs:
          module: 'PSRule.Rules.Azure'

      - task: AzurePowerShell@5
        inputs:
          azureSubscription: 'my.secret.subscription'
          ScriptType: 'InlineScript'
          Inline: |
            Get-AzContext;
            Export-AzRuleData -OutputPath 'out/templates/';
            Assert-PSRule -Module 'PSRule.Rules.Azure' -InputPath 'out/templates/';
          azurePowerShellVersion: 'LatestVersion'
```

**Expected behaviour**

Expecting a list of results, either failed or passed
```text
   TargetName: storage

RuleName                            Outcome    Recommendation
--------                            -------    --------------
Azure.Storage.UseReplication        Fail       Storage accounts not using GRS may be at risk
Azure.Storage.SecureTransferRequ... Fail       Storage accounts should only accept secure traffic
Azure.Storage.SoftDelete            Fail       Enable soft delete on Storage Accounts
```

**Error output**

```text
Starting: AzurePowerShell
==============================================================================
Task         : Azure PowerShell
Description  : Run a PowerShell script within an Azure environment
Version      : 5.185.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azurepowershelltroubleshooting
==============================================================================
Generating script.
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . '/home/vsts/work/_temp/24557fd4-f72a-4833-9302-dc3ac648989a.ps1'
Saved!
Import-Module -Name /home/vsts/.local/share/powershell/Modules/Az.Accounts/2.6.0/Az.Accounts.psd1 -Global
Clear-AzContext -Scope Process
Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
Connect-AzAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud @processScope
 Set-AzContext -SubscriptionId ... -TenantId ***

Name                                     Account   Subscript Environme TenantId
                                                   ionName   nt
----                                     -------   --------- --------- --------
my.secret.subscription      (z4x212y8-5e… z1x8y5c4… my.secre… AzureClo… a17bcde…
Get-AzRoleAssignment: /home/vsts/.local/share/powershell/Modules/PSRule.Rules.Azure/1.9.0/PSRule.Rules.Azure.psm1:1137
Line |
1137 |  … esources += Get-AzRoleAssignment -DefaultProfile $Context -Scope $Res …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception of type 'Microsoft.Rest.Azure.CloudException' was
     | thrown.

##[error]PowerShell exited with code '1'.
Finishing: AzurePowerShell

```

**Module in use and version:**

- Azure Devops extension: 1.3.0
- PSRule.Rules.Azure: 1.9.0
- PSRule: 1.8.0

Captured output from `$PSVersionTable`:

```text
Azure PowerShell version: 5.185.0
```

Running this on the `ubuntu-latest` [Microsoft-hosted](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#powershell-tools) agent.
