### ISSUE TITLE
Provide configuration to set required parameters

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#1065]
Currently any required parameters must be specified in parameter files for templates to be expanded.

Some pipelines may specify required parameters on the command line.

To provide better support for this scenario we should introduce a fallback configuration value that can be set with parameters. i.e. `AZURE_PARAMETER_DEFAULTS`.

For example:

```yaml
configuration:
  AZURE_PARAMETER_DEFAULTS:
    location: 'eastus'
    storageAccountName: 'st001'
```

**Behaviour**

When `AZURE_PARAMETER_DEFAULTS` is set:

- Template parameter file value will be used is set.
- Template parameter `defaultValue` be used when the parameters file value is not set.
- If there is no `defaultValue` but a matching key of `AZURE_PARAMETER_DEFAULTS` exists, use that.
