### ISSUE TITLE
Module in module support

### ISSUE THREAD

**Issue by Dylan-Prins** [Azure/PSRule.Rules.Azure#1548]
**Is your feature request related to a problem? Please describe.**

Supporting moduleception (modules in modules). We have the following set-up:

_main.bicep -> local modules with resource group deployments -> acr modules._

This means the resources are not getting evaluated, because only deployments in deployments are tested.

This is what works:
`(Get-Content template.json | ConvertFrom-Json -Depth 99).resources[0].properties.template.resources | Assert-PSRule -Format Json`

But I was hoping to use the azure pipeline task:

```yaml
  - task: ps-rule-assert@2
    displayName: Analyze Azure template files
    inputs:
      inputType: repository
      modules: "PSRule.Rules.Azure"
      outputFormat: NUnit3
      outputPath: reports/ps-rule-results.xml
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
