### ISSUE TITLE
Self-hosted windows agent powershell error code 5

### ISSUE THREAD

**Issue by maxricketts** [Azure/PSRule.Rules.Azure#1901]
**Description of the issue**

Random pipelines fail with the below error

```powershell
##[error]Exit code 5 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\a\_tasks\ps-rule-assert_8804fc31-b62f-4d49-b2a1-c80dc0879dae\2.6.2211067\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\a\_tasks\ps-rule-assert_8804fc31-b62f-4d49-b2a1-c80dc0879dae\2.6.2211067\powershell.ps1'''))"'
```
**Module in use and version:**

```text
Checking PSRule
[info] Using repository: PSGallery
[info] Installing PSRule: 2.6.0
Checking modules
> Checking module: PSRule.Rules.Azure
  - Installing module
  - Using version: 1.21.2
Checking environment
[info] Using PSRule: 2.6.0
[info] Using Extension: 2.6.0
[info] Using Task: 2.6.2211067
[info] Using Workspace: C:\a\1\s
[info] Using PWD: C:\a\_tasks\ps-rule-assert_8804fc31-b62f-4d49-b2a1-c80dc0879dae\2.6.2211067
[info] Using Path: C:\a\1\s
[info] Using Source: C:\a\1\s\.ps-rule\
[info] Using Baseline: 
[info] Using Conventions: 
[info] Using InputType: repository
[info] Using InputPath: C:\a\1\s\newImage\bicep\
[info] Using Option: 
[info] Using Outcome: 
[info] Using OutputFormat: Nunit3
[info] Using OutputPath: C:\a\1\s\rule-report.xml
```

**Comment by BernieWhite** [comment]
@maxricketts Ok so error code 5 reported by PowerShell indicates an access denied error. This could happen both for inputs and outputs.

With `OutputPath` set to `rule-report.xml` I don't think it is related to the outputs.

This looks like a problem. `Using Source: C:\a\1\s.ps-rule` which would not be valid.

Are you able to provide the pipeline YAML code for the `ps-rule-assert@2` task and any settings configured within `ps-rule.yaml` under the `input:` and `output:` keys.

Also this discussion may help: https://github.com/microsoft/PSRule-pipelines/discussions/387

**Comment by maxricketts** [comment]
Here is the yaml for the psrule stage.  This happens randomly, even when no changes have been applied to the code or yaml.  Run the pipeline again and it will work.  This does look like the same issue as `387` but I have the inputType set to repository and still get the random occurence or error code 5.

Please let me know if you require any more information.

```yaml
# yaml-language-server: $schema=./deploy.yml

stages: 
  - stage: PSRuleScanning
    displayName: PSRule validation and governance
    jobs:
      - job: PSRule
        displayName: Checkout and scan code
        steps:
          - checkout: Exg.DevOps.ImageBuilder
            # Analyze Azure resources using PSRule for Azure
          - task: ps-rule-assert@2
            displayName: Analyze Azure bicep files
            inputs:
              modules: PSRule.Rules.Azure
              inputType: repository
              inputPath: newImage/bicep/
              outputFormat: Nunit3
              outputPath: rule-report.xml
            env:
              # Define environment variables within Azure Pipelines
              AZURE_CLIENT_ID: $(psrule-clientid)
              AZURE_CLIENT_SECRET: $(psrule-secret)
              AZURE_TENANT_ID: $(psrule-tenant)
          # PSRule results
          - task: PublishTestResults@2
            displayName: 'Publish PSRule results'
            inputs:
              testRunTitle: 'PSRule'
              testRunner: NUnit
              testResultsFiles: 'rule-report.xml'
              mergeTestResults: true
              publishRunAttachments: true
            condition: succeededOrFailed()
```

**Comment by BernieWhite** [comment]
@maxricketts Looks like the missing `\` was just how the output sample was pasted. The paths look correct now as a text block.

The task parameters look fine.

We're going need to collect more information. You can enable verbose output by setting the `SYSTEM_DEBUG` pipeline variable to `true`.

**Comment by maxricketts** [comment]
I have attached the logs for you.  It seems like it always fails the first time on a fresh vm instance on the scale set.  run it again and its fine.  I have also attached a log of when it runs all ok at the bottom

[psrulepipelinedebug.txt](https://github.com/Azure/PSRule.Rules.Azure/files/10094153/psrulepipelinedebug.txt)

[pipelinelogcompleted.txt](https://github.com/Azure/PSRule.Rules.Azure/files/10094207/pipelinelogcompleted.txt)

**Comment by BernieWhite** [comment]
@maxricketts Thanks for the logs. From the logs, PSRule is running and it starting to process files. It start to expand a Bicep file here:

```text
2022-11-25T16:13:58.1294941Z ##[debug][Azure.ExpandBicep] -- Expanding bicep source: C:\a\1\s\newImage\bicep\imagebuilder.bicep
```

That's the last action in the logs.

With your VMSS setup, do you have additional custom scripts that might be running in the background while this job is running?

**Comment by BernieWhite** [comment]
@maxricketts Also additionally, I've added some additional verbose logging for testing in pre-release v1.22.0-B0203. This might help confirm if the Bicep compile is definitely the cause of the failure.

To use the pre-release you will need to enable the pre-release by setting the `prerelease: true` input parameter for the `ps-rule-assert@2` task.

**Comment by maxricketts** [comment]
@BernieWhite - I have added `prerelease: true` - and I am getting the below error.
```yaml
          - task: ps-rule-assert@2
            displayName: Analyze Azure bicep files            
            inputs:
              prerelease: true
              modules: PSRule.Rules.Azure
              inputType: repository
              inputPath: newImage/bicep/
              outputFormat: Nunit3
              outputPath: rule-report.xml
```

##[error]An error occurred installing a dependency module. A parameter cannot be found that matches parameter name 'AllowPrerelease'.
