### ISSUE TITLE
Use policy definition name when generating a rule from it

### ISSUE THREAD

**Issue by VeraBE** [Azure/PSRule.Rules.Azure#1959]
Policy definitions have a name that explains with a few words the main goal of the policy, and that is not being used when generating rules from policies

![image](https://user-images.githubusercontent.com/11780216/207982093-532e77df-25bd-4c2e-a277-9b6655291a9f.png)

I think it would be nice for that information to populate `ruleRecord.Info.DisplayName` in the C# library of PSRule, like the native rules do, instead of outputting the ID (Azure.Policy.\<hash\>) there too. I'm trying to do a PR with the change but I don't understand where I can add that information in the YAML rule so that it ends up reflected in that C# property, while also having the Azure.Policy.\<hash\> information in `ruleRecord.RuleName`, any advice will be appreciated

**Comment by BernieWhite** [comment]
@VeraBE Good idea. I was thinking about this too. PSRule supports localization within [documentation/ help](https://microsoft.github.io/PSRule/v2/authoring/writing-rule-help/#writing-markdown-documentation). Currently there is some properties that can only be set via creating rule help markdown files. The display name is one such property, otherwise PSRule such just return the name of the rule as the display name for most practise cases. For rule help, each rule is has one markdown file per rule per locale.

I'm not sure we want to generate markdown documentation for just for a display name, but if a customer needs to handle multiple languages then we might need to. Built-in policies aside, I've never seen a customer author custom policies with multiple languages, although maybe some customers do.

I guess the question is if a policy as rule fails, what information should we show? Normally, PSRule would show reasons, recommendation, and an online link which is also true for BPA.

---

Separately, I think that customers would find the ability to set a non-localized `displayName` and `recommendation` property helpful so I'm inclined to do this regardless of what we do with Azure Policy. But it would be easy enough to the JSON export process.

```yaml
---
# Synopsis: Storage Accounts should only accept explicitly allowed traffic.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Storage.Firewall
  ref: AZR-000202
  tags:
    release: 'GA'
    ruleSet: '2021_09'
  displayName: 'Configure Azure Storage firewall'
  recommendation: 'Consider configuring storage firewall to restrict network access to permitted clients only. Also consider enforcing this setting using Azure Policy.'
spec:
  type:
  - Microsoft.Storage/storageAccounts
  with:
  - Azure.Usage.NotCloudShell
  condition:
    field: properties.networkAcls.defaultAction
    equals: deny

```

**Comment by VeraBE** [comment]
Ohhh, I see now

Adding those properties to the metadata sounds good to me

Regarding what we want to show, in TemplateAnalyzer for each result we need the rule ID, rule name, help URI, short description, full description, and recommendation. Because so far we are only looking at assignments with default parameter values, I've been using the policy definition ID as rule ID, for the help URI: `https://portal.azure.com/#view/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2F" + ruleId`, I want to use the policy definition name for the short description, and for the full description I don't see any information on the policy definition that we can leaverage so I've been reusing the recomendation for now :/

**Comment by BernieWhite** [comment]
@VeraBE Ok I think we have all that covered. Updating the structure slightly to align with other aspects:

Synopsis is short description.

`metadata.description` property would be the full description.
`spec.recommend` property would be the recommendation.
`metadata.link` property would be the help URL.

```yaml
---
# Synopsis: Storage Accounts should only accept explicitly allowed traffic.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Storage.Firewall
  ref: AZR-000202
  tags:
    release: 'GA'
    ruleSet: '2021_09'
  displayName: 'Configure Azure Storage firewall'
  description: By default, storage accounts accept connections from clients on any network. To limit access to selected networks, you must first change the default action.
  link: https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Storage.Firewall/
spec:
  recommend: 'Consider configuring storage firewall to restrict network access to permitted clients only. Also consider enforcing this setting using Azure Policy.'
  type:
  - Microsoft.Storage/storageAccounts
  with:
  - Azure.Usage.NotCloudShell
  condition:
    field: properties.networkAcls.defaultAction
    equals: deny
```
