### ISSUE TITLE
Add GPT based code review CI

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#2242]
Are we open for adding a  GPT based code review CI?

It's breaking and cutting edge, but it would have been interesting to have this on our PRs and see what kind of suggestions would be emitted and if they are of any value in the cycle. There is already a Microsoft repository that have taken it in use.

https://github.com/microsoft/gpt-review

Example workflow:

```yml
name: GPT Review on Pull Request

on:
  pull_request_target:
    branches: [main]

jobs:
  add_pr_comment:
    runs-on: ubuntu-latest
    name: OpenAI PR Comment
    steps:
      - id: review
        uses: microsoft/gpt-review@v0.9.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_OPENAI_API: ${{ secrets.AZURE_OPENAI_API }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
```

Example suggestions provided:

https://github.com/microsoft/SynapseML/pulls
