### ISSUE TITLE
[BUG] SQL AVM Flagging false positives

### ISSUE THREAD

**Issue by riosengineer** [Azure/PSRule.Rules.Azure#3146]
### Description of the issue

Hey @BernieWhite - hope you're well. 

I am triggering these following rules: 

- Azure.Deployment.SecureParameter (AZR-000408)
- Azure.Deployment.AdminUsername (AZR-000284)
Running:
`PSRule v2.9.0
PSRule.Rules.Azure v1.38.0
`

When I am deploying the latest AVM for Azure SQL PaaS. I am actually passing an Entra security group for the login username and even with the `()secure` param on this it still flags. I thought it would  remove the alert by doing that to bypass it but no luck. I think this may be related or the same as: https://github.com/Azure/PSRule.Rules.Azure/issues/2813 ?

```
  Recommend:
  Sensitive properties should be passed as parameters. Avoid using deterministic
  values for sensitive properties.

  Reason:
  - The property 'administratorLogin' uses a deterministic literal value.
  - The property 'administratorLoginPassword' uses a deterministic literal value.

  Help:
  - https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Deployment.AdminUsername/
```

I am also getting a keys flag when I'm not using keys. I feel it is expanding the source module of the AVM SQL and maybe there is an issue from that. 

 ```
Recommend:
  Consider using secure parameters for parameters that contain sensitive
  information.

  Reason:
  - Path keys: The parameter 'keys' with type 'array' is not secure.

  Help:
  - https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Deployment.SecureParameter/
  ```

I know it's the AVM SQL because if I remove the module from my template, both these flags are not present. The source code is here: https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/sql/server/main.bicep

Running the latest 

Is this a potential bug? Thanks

### Reproduction

Relevant code context to repro:

Param:
```bicep
  sqlDatabase: {
      name: 'sqldb'
      tier: 'Basic'
      sku: 'Basic'
      maxSizeBytes: 2147483648
      collation: 'SQL_Latin1_General_CP1_CI_AS'
    }
  sqlAdministrators: {
      azureADOnlyAuthentication: true
      login: 'Some_Entra_Group'
      sid: 'asidhere'
      principalType: 'Group'
    }
  }
```

Template:
```bicep
// Azure SQL DB
module sqlDb 'br/public:avm/res/sql/server:0.8.0' = {
  name: '${uniqueString(deployment().name, location)}-sql'
  scope: resourceGroup(rgName)
  params: {
    name: sqlServerName
    location: location
    minimalTlsVersion: '1.2'
    managedIdentities: {
      systemAssigned: true
    }
    privateEndpoints: [
      {
        name: 'pe'
        customNetworkInterfaceName: 'pe-sql-nic'
        subnetResourceId: vNet.outputs.subnetResourceIds[1]
        privateDnsZoneGroup: {
          privateDnsZoneGroupConfigs: [
            {
              privateDnsZoneResourceId: privateDNSZoneSql.id
            }
          ]
        }
      }
    ]
    publicNetworkAccess: 'Disabled'
    securityAlertPolicies: [
      {
        name: 'Default'
        state: 'Enabled'
        emailAccountAdmins: true
      }
    ]
    administrators: {
      azureADOnlyAuthentication: sqlAdministrators.azureADOnlyAuthentication
      login: sqlAdministrators.login
      sid: sqlAdministrators.sid
      principalType: sqlAdministrators.principalType
    }
    databases: [
      {
        name: sqlDatabase.name
        collation: sqlDatabase.collation
        maxSizeBytes: sqlDatabase.maxSizeBytes
        skuTier: sqlDatabase.tier
        skuName: sqlDatabase.sku
      }
    ]
    tags: union(tags, { Created: timeNow })
  }
}
```

### Version of PSRule

2.9.0
