### ISSUE TITLE
[BUG] require `tags` in defaults test

### ISSUE THREAD

**Issue by xhy8759** [Azure/PSRule.Rules.Azure#3283]
### Existing rule

Azure.Resource.UseTags

### Description of the issue

https://github.com/Infrastructure-as-code-Automation/bicep-registry-modules/actions/runs/13902291416
In defaults test, it requires `tags` for my resouce:
```
resource managedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2018-11-30' = {
  name: 'temp'
  location: location
  tags: tags
}

resource generateSSHKey 'Microsoft.Resources/deploymentScripts@2020-10-01' = if (empty(linuxProfile)) {
  name: 'generateSSHKey'
  location: location
  tags: tags
  kind: 'AzurePowerShell'
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${managedIdentity.id}': {}
    }
  }
  properties: {
    azPowerShellVersion: '8.0'
    retentionInterval: 'P1D'
    scriptContent: '''
      # Create temp directory in a known location
      $tempDir = "/tmp/sshkeys"
      New-Item -ItemType Directory -Path $tempDir -Force
      Set-Location $tempDir
      # Generate SSH key pair using ssh-keygen
      ssh-keygen -t rsa -b 4096 -f ./key -N '""' -q
      # Read the generated keys
      $publicKey = Get-Content -Path "./key.pub" -Raw
      $privateKey = Get-Content -Path "./key" -Raw
      # Clean up temp files
      Remove-Item -Path "./key*" -Force
      Remove-Item -Path $tempDir -Force -Recurse
      # Set output
      $DeploymentScriptOutputs = @{}
      $DeploymentScriptOutputs['publicKey'] = $publicKey
      $DeploymentScriptOutputs['privateKey'] = $privateKey
    '''
  }
}
```
While I attach `tags` for these two tests, but in default test, I don't need to pass tags.

### Reproduction

Run the workflow.

### Version of PSRule

2.9.0

**Comment by BernieWhite** [comment]
Hi @xhy8759, Within AVM pipelines there is a special exclusion for resources from the defaults that normally ignores this rule.

In AVM this is implemented as a suppression group based on a naming convention, a resource name containing `min`. This would normally be populated from the `serviceShort` name.

Currently you are hardcoding the name of the two resources in question, so this suppression is not applying.

Some options on how you could solve this:

1. If you can update the resource `name:` of these two resource to include the value set by `param name` maybe `name: 'generateSSHKey-${name}'`, this would solve your issue and align the existing suppression configuration. Alternatively, you could expose a separate parameter for setting the name of these two resources then override the name to include `min` from your defaults test Bicep.
2. Create a custom suppression for your issue. By creating a suppression group, under `utilities/pipelines/staticValidation/psrule/.ps-rule/` however, you might want to reference this issue or ask a question on the internal _Bicep specific discussion_ chat so that it's clear why you are doing this for your PR.

---

Creating a suppression group like the following in a file named something like `resource-tags-suppress.Rule.yaml`:

```yaml
---
# Synopsis: Suppress tagging rules for statically named module resources on default tests.
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: "SuppressTagsForDefaults"
spec:
  rule:
    - Azure.Resource.UseTags
  if:
    source: Template
    withinPath:
      - avm/res/hybrid-container-service/provisioned-cluster-instance/tests/e2e/defaults/main.test.bicep
```

---

I hope that helps.
